### ISSUE TITLE
Confidentiality and Possession of Private Key Material

### ISSUE THREAD

**Issue by christiansmith** [mitmedialab/TrustCoreID#2]
For this demo, we require users to maintain possession of their private keys. These must not be stored on a server and should not otherwise be accessible to anyone other than the owner. 

Please discuss additional relevant security considerations and technical approaches in this issue.

**Comment by dazzaji** [comment]
The proposed solution is an Electron-based desktop app with keys generated and stored on the user's device after installation or during registration. We may need to take additional steps to prevent leakage, such as encrypting keys on disk. 
[NOTE: I extracted/moved these two sentences from the initial comment by @christiansmith to separate the requirements from the proposed solution]

**Comment by dazzaji** [comment]
When an issue is meant to be a requirement (or constraint/expectation/assumption/etc) how about using the initial comment to hone the requirement statement and (as you suggest) subsequent comments to discuss/flesh out proposed solutions or refine the requirement as needed.  When people want to fully embody a solution, they can just just point to assets elsewhere in the repo like a diagram image, a wiki page and of course the code itself.

Since most issues won't be requirements, I made a "[requirements](https://github.com/mitmedialab/TrustCoreID/labels/requirements)" label to make it easy to identify/sort/filter requirements.
